### ISSUE TITLE
Dish disappearing

### ISSUE THREAD

**Issue by feherneoh** [Abhinav1997/NekoCollector#1]
After catching the first cat and placing a new dish, app will say that the same cat came back when I re-enter it if I did not close it before.

How to reproduce:
Place dish, press home button, open app again without removing it from recents

**Comment by Abhinav1997** [comment]
Which android version are you using? I did try the steps you mentioned but didn't face any issue. Can you elaborate the problem?

**Comment by feherneoh** [comment]
I'm using 6.0.1, Sony stock, no root, bootloader locked.
I place a dish, press the home button, then tap on the app's icon in my launcher, and the dish just disappeares (Now I don't get the message about the same cat showing up, it just disappeares).

**Comment by feherneoh** [comment]
https://www.youtube.com/watch?v=hGNaL2D27OU

**Comment by Abhinav1997** [comment]
Fixed it, thanks for reporting. Expect an update soon.
