### ISSUE TITLE
Force close landscape mode

### ISSUE THREAD

**Issue by Pikoulol** [Abhinav1997/NekoCollector#16]
Hi,
I'm getting a force close of the app everytime I rotate my phone.

Model : Nexus 5
Android version : 6.0.1

It seems okay on Android 7 Nexus 5X

**Comment by Abhinav1997** [comment]
Can you submit a log?

**Comment by Abhinav1997** [comment]
https://github.com/Abhinav1997/NekoCollector/commit/110a7dea0555e4dca25dc3a173e7b175db8f6a19

This should fix it.
