### ISSUE TITLE
No Cats Arrive 

### ISSUE THREAD

**Issue by WhenPenguinsAttack** [Abhinav1997/NekoCollector#2]
I am using a Samsung Galaxy Avant running on Android 4.4.2, and after installing the app, there are no cats at all.  I leave the food out for hours, and no cats come.  Exiting out of the app and doing a force stop does not help at all.  Neither does restarting the phone or uninstalling and then reinstalling the app.

**Comment by Abhinav1997** [comment]
I've been getting complaints of this happening pre-lollipop. I have only tried in emulators and it did work but I'll install kitkat on an older phone of mine and test. Will fix if there's an issue.

**Comment by WhenPenguinsAttack** [comment]
Thanks!  :)

**Comment by Abhinav1997** [comment]
Fixed it, thanks for reporting. Expect an update soon.

**Comment by WhenPenguinsAttack** [comment]
Thanks!  :)
